name: deploy

on:
  workflow_run:
    workflows: ['test']
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
      - name: Checkout source (from test workflow)
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - uses: pnpm/action-setup@v4
        with:
          version: 10.*
      - run: pnpm install
      - run: pnpm run generate:posts
      - run: pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
